name: Build and Deploy JSDoc Docs
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v1
        -   name: Install Dependencies
            run: npm install
        -   name: Generate Documentation
            run: npm run jsdoc
        -   name: Build and Deploy
            uses: JamesIves/github-pages-deploy-action@releases/v3
            with:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                BASE_BRANCH: master # The branch the action should deploy from.
                BRANCH: gh-pages # The branch the action should deploy to.
                FOLDER: docs # The folder the action should deploy.
